Checktify.Web/Areas/User/Components/LayoutViewComponent.cs
using Checktify.Entity.Identity.Entities;
using Checktify.Entity.Identity.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Checktify.Web.Areas.User.Components
{
    public class LayoutViewComponent : ViewComponent
    {
        private readonly UserManager<AppUser> userManager;

        public LayoutViewComponent(UserManager<AppUser> userManager)
        {
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync(string Username)
        {
            if (Username == null)
            {
                Username = User.Identity!.Name!;
            }

            var user = await userManager.FindByNameAsync(Username);

            if (user!.FileName == null)
            {
                return View(new UserPictureVM { FileName = "Default"});
            }


            return View(new UserPictureVM { FileName = user.FileName });
        }
    }
}

Checktify.Web/Areas/User/Controllers/AuthenticationUserController.cs
using AutoMapper;
using Checktify.Core.Enumerators;
using Checktify.Entity.Identity.Entities;
using Checktify.Entity.Identity.ViewModels;
using Checktify.Service.Helpers.Generic.Image;
using Checktify.Service.Helpers.Identity;
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Checktify.Web.Areas.User.Controllers
{
    [Authorize]
    [Area("User")]
    public class AuthenticationUserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly IMapper _mapper;
        private readonly IValidator<UserEditVM> _userEditValidator;
        private readonly IImageHelper _imageHelper;

        public AuthenticationUserController(UserManager<AppUser> userManager, IMapper mapper, IValidator<UserEditVM> userEditValidator, SignInManager<AppUser> signInManager, IImageHelper imageHelper)
        {
            _userManager = userManager;
            _mapper = mapper;
            _userEditValidator = userEditValidator;
            _signInManager = signInManager;
            _imageHelper = imageHelper;
        }

        [HttpGet]
        public async Task<ActionResult> UserEdit()
        {
            var user = await _userManager.FindByNameAsync(User.Identity!.Name!);
            var userEditVm = _mapper.Map<UserEditVM>(user);
            return View(userEditVm);
        }

        [HttpPost]
        public async Task<ActionResult> UserEdit(UserEditVM request)
        {
            var user = await _userManager.FindByNameAsync(User.Identity!.Name!);

            var validation = await _userEditValidator.ValidateAsync(request);
            if(!validation.IsValid)
            {
                validation.AddToModelState(this.ModelState);
                return View();
            }

            var passwordCheck = await _userManager.CheckPasswordAsync(user!, request.Password);
            if(!passwordCheck)
            {
                ViewBag.Result = "IncorrectPassword";
                ModelState.AddModelErrorsList(new List<string> { "Current password is incorrect." } );

                return Redirect(nameof(UserEdit));
            }

            if (request.NewPassword != null)
            {
                var passwordChangeResult = await _userManager.ChangePasswordAsync(user!, request.Password, request.NewPassword);
                if (!passwordChangeResult.Succeeded)
                {
                    ViewBag.Result = "PasswordChangeFailed";
                    ModelState.AddModelErrorsList(passwordChangeResult.Errors.Select(e => e.Description).ToList());
                    return Redirect(nameof(UserEdit));
                }
            }

            var oldFileName = user!.FileName;
            var oldFileType = user!.FileType;

            if (request.Photo != null)
            {
                var image = await _imageHelper.ImageUplaod(request.Photo, ImageType.identity, null);

                if (image.Error != null)
                {
                    if (request.NewPassword != null)
                    {
                        await _userManager.ChangePasswordAsync(user!, request.NewPassword, request.Password);
                        await _userManager.UpdateSecurityStampAsync(user);
                        await _signInManager.SignOutAsync();
                        await _signInManager.SignInAsync(user, false);
                    }

                    return Redirect(nameof(UserEdit));
                }

                request.FileName = image.Filename;
                request.FileType = request.Photo.ContentType;
            } else
            {
                request.FileName = oldFileName;
                request.FileType = oldFileType;
            }

            var mappedUser = _mapper.Map(request, user);
            var userUpdate = await _userManager.UpdateAsync(mappedUser);
            if (userUpdate.Succeeded)
            {
                if(request.Photo != null)
                {
                    if (oldFileName != null && oldFileType != null)
                    {
                        _imageHelper.DeleteImage(oldFileName);
                    }
                }

                await _userManager.UpdateSecurityStampAsync(user);
                await _signInManager.SignOutAsync();
                await _signInManager.SignInAsync(user, false);

                return RedirectToAction("Index", "Dashboard", new { area = "User" });
            }

            if (request.FileName != null)
            {
                _imageHelper.DeleteImage(request.FileName);
            }

            if (request.NewPassword != null)
            {
                await _userManager.ChangePasswordAsync(user!, request.NewPassword, request.Password);
                await _userManager.UpdateSecurityStampAsync(user);
                await _signInManager.SignOutAsync();
                await _signInManager.SignInAsync(user, false);
            }

            ViewBag.Username = user.UserName;
            return Redirect(nameof(UserEdit));
        }
    }
}

Checktify.Web/Areas/User/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Checktify.Web.Areas.User.Controllers
{
    [Authorize]
    [Area("User")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Checktify.Web/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx" class="js">

<head>
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A powerful and conceptual apps base dashboard template that especially build for developers and programmers.">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="~/Admin/src/images/favicon.png">
    <!-- Page Title  -->
    <title>Checktify</title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="~/Admin/src/assets/css/dashlite.css?ver=3.0.3">
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <link id="skin-default" rel="stylesheet" href="~/Admin/src/assets/css/theme.css?ver=3.0.3">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
</head>

<body class="nk-body bg-lighter npc-general has-sidebar ">
    <div class="nk-app-root">
        <!-- main @@s -->
        <div class="nk-main ">
            <!-- sidebar @@s -->
            <div class="nk-sidebar nk-sidebar-fixed is-dark " data-content="sidebarMenu">
                <div class="nk-sidebar-element nk-sidebar-head">
                    <div class="nk-menu-trigger">
                        <a href="#" class="nk-nav-toggle nk-quick-nav-icon d-xl-none" data-target="sidebarMenu"><em class="icon ni ni-arrow-left"></em></a>
                        <a href="#" class="nk-nav-compact nk-quick-nav-icon d-none d-xl-inline-flex" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
                    </div>
                    <div class="nk-sidebar-brand">
                        <a href="html/crm/index.html" class="logo-link nk-sidebar-logo">
                            <img class="logo-light logo-img" src="~/Admin/src/images/logo.png" srcset="./images/logo2x.png 2x" alt="logo">
                            <img class="logo-dark logo-img" src="~/Admin/src/images/logo-dark.png" srcset="./images/logo-dark2x.png 2x" alt="logo-dark">
                        </a>
                    </div>
                </div><!-- .nk-sidebar-element -->
                <div class="nk-sidebar-element nk-sidebar-body">
                    <div class="nk-sidebar-content">
                        <div class="nk-sidebar-menu" data-simplebar>

							@await Component.InvokeAsync("Layout", ViewBag.Username);

                            <ul class="nk-menu">
                                <li class="nk-menu-item">
                                    <a asp-area="User" asp-controller="Dashboard" asp-action="Index" class="nk-menu-link">
                                        <span class="nk-menu-icon"><i class="bi bi-columns-gap"></i></span>
                                        <span class="nk-menu-text">Dashboard</span>
                                    </a>
                                </li><!-- .nk-menu-item -->

                                <li class="nk-menu-item">
                                    <a asp-area="User" asp-controller="Attendance" asp-action="AddAttendance" class="nk-menu-link">
                                        <span class="nk-menu-icon"><i class="bi bi-calendar-week-fill"></i></span>
                                        <span class="nk-menu-text">Attendance</span>
                                    </a>
                                </li><!-- .nk-menu-item -->

                                <li class="nk-menu-heading">
                                    <h6 class="overline-title text-primary-alt">Settings</h6>
                                </li>

                                <li class="nk-menu-item">
                                    <a asp-area="User" asp-controller="AuthenticationUser" asp-action="UserEdit" class="nk-menu-link">
                                        <span class="nk-menu-icon"><i class="bi bi-gear-fill"></i></span>
                                        <span class="nk-menu-text">User Setting</span>
                                    </a>
                                </li><!-- .nk-menu-item -->

                            </ul><!-- .nk-menu -->
                        </div><!-- .nk-sidebar-menu -->
                    </div><!-- .nk-sidebar-content -->
                </div><!-- .nk-sidebar-element -->
            </div>
            <!-- sidebar @@e -->
            <!-- wrap @@s -->
            <div class="nk-wrap ">

                <!-- main header @@e -->
                <!-- content @@s -->
                <div class="nk-content ">
                    @RenderBody()
                </div>
                <!-- content @@e -->
            </div>
            <!-- wrap @@e -->
        </div>
        <!-- main @@e -->
    </div>
    <!-- app-root @@e -->
    <!-- JavaScript -->
    <script src="~/Admin/src/assets/js/bundle.js?ver=3.0.3"></script>
    <script src="~/Admin/src/assets/js/scripts.js?ver=3.0.3"></script>
    <script src="~/Admin/src/assets/js/charts/chart-crm.js?ver=3.0.3"></script>
</body>

</html>